// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESrZR7eVzE3wN9CLd02TURr1A8HMdlLA',
    appId: '1:626916661311:android:aa33140c5dc0a68102008a',
    messagingSenderId: '626916661311',
    projectId: 'vocsy-cc-pro-fitness',
    storageBucket: 'vocsy-cc-pro-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHA9KjT0SZ5pyteOWGpJ9XgxG0Fn5AiFk',
    appId: '1:626916661311:ios:d8d4a708e635ef1802008a',
    messagingSenderId: '626916661311',
    projectId: 'vocsy-cc-pro-fitness',
    storageBucket: 'vocsy-cc-pro-fitness.appspot.com',
    androidClientId: '626916661311-5ssdedvj42irt4unfalg7esmsm22vbdt.apps.googleusercontent.com',
    iosClientId: '626916661311-ambub1cc5dda3fje4p2g6jbrbs8aghk7.apps.googleusercontent.com',
    iosBundleId: 'com.vocsy.cc.fitness',
  );

}